export type { Client, ClientAddress, CreateClientInput, UpdateClientInput } from "./client";
export type { Procedure, CreateProcedureInput, UpdateProcedureInput } from "./procedure";
export type { Appointment, CreateAppointmentInput, UpdateAppointmentInput } from "./appointment";
export type { Payment, PartialPaymentRecord, CreatePaymentInput } from "./payment";
export type { TimeSlot, BlockedDate } from "./time-slot";
export type { Anamnesis, CreateAnamnesisInput, LashMapping, AnamnesisHairLoss, AnamnosisProcedureType } from "./anamnesis";
export type { Material, CreateMaterialInput, UpdateMaterialInput } from "./material";
export type { StockMovement, CreateStockMovementInput } from "./stock-movement";
export type { Expense, CreateExpenseInput, UpdateExpenseInput } from "./expense";
export type { ReminderTemplate, ReminderVariables } from "./reminder";
export { REMINDER_TEMPLATES } from "./reminder";
export type { WhatsAppTemplate, CreateWhatsAppTemplateInput, UpdateWhatsAppTemplateInput, TemplateVariables } from "./whatsapp-template";
export { TEMPLATE_VARIABLE_LABELS } from "./whatsapp-template";
export type { ExtraService, ExtraServiceType, CreateExtraServiceInput, UpdateExtraServiceInput } from "./extra-service";
